"""Add is_waitlist to CourseRegistration

Revision ID: 076a37e3054d
Revises: 3c0b2c459be9
Create Date: 2026-01-10 20:07:11.593121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076a37e3054d'
down_revision = '3c0b2c459be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art_categories', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('course_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_waitlist', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_registrations', schema=None) as batch_op:
        batch_op.drop_column('is_waitlist')

    with op.batch_alter_table('art_categories', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
