"""Add num_participants to CourseRegistration

Revision ID: 2cad5a20d023
Revises: 076a37e3054d
Create Date: 2026-01-10 20:17:31.860197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cad5a20d023'
down_revision = '076a37e3054d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_participants', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_registrations', schema=None) as batch_op:
        batch_op.drop_column('num_participants')

    # ### end Alembic commands ###
