"""Add card_image_path to WorkshopCategory

Revision ID: 30c0aa3ec5a4
Revises: e39bf7e2c145
Create Date: 2026-01-10 16:30:55.267400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c0aa3ec5a4'
down_revision = 'e39bf7e2c145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_categories', schema=None) as batch_op:
        batch_op.drop_column('card_image_path')

    # ### end Alembic commands ###
