"""Add no_dates_text to WorkshopCategory

Revision ID: 3c0b2c459be9
Revises: 30c0aa3ec5a4
Create Date: 2026-01-10 19:18:33.120707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0b2c459be9'
down_revision = '30c0aa3ec5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_dates_text', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_categories', schema=None) as batch_op:
        batch_op.drop_column('no_dates_text')

    # ### end Alembic commands ###
