"""Add WorkshopCategory and update Course model

Revision ID: 4d3ab0e994c1
Revises: 
Create Date: 2026-01-10 14:30:38.915978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3ab0e994c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workshop_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_info', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_url', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(None, 'workshop_categories', ['workshop_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_url')
        batch_op.drop_column('cost')
        batch_op.drop_column('time_info')
        batch_op.drop_column('workshop_category_id')

    op.drop_table('workshop_categories')
    # ### end Alembic commands ###
